"""
Markdown formatter for generating markdown-formatted newsletters.
"""

from src.models.newsletter import Newsletter, NewsletterItem
from src.publishing.formatters.base_formatter import BaseFormatter


class MarkdownFormatter(BaseFormatter):
    """Format newsletters as markdown files."""

    # Category display names with emojis
    CATEGORY_NAMES = {
        "research": "📚 Research Papers",
        "product": "🚀 New Products",
        "funding": "💰 Funding & M&A",
        "news": "📰 Industry News",
        "breakthrough": "⚡ Breakthroughs",
        "regulation": "⚖️ Policy & Regulation",
    }

    def __init__(self):
        super().__init__("markdown")

    def format(self, newsletter: Newsletter) -> str:
        """
        Generate markdown-formatted newsletter.

        Args:
            newsletter: Newsletter object to format

        Returns:
            Markdown-formatted string
        """
        sections = []

        # Header
        sections.append(f"# AI Newsletter - {newsletter.date}")
        sections.append(f"\n**Published:** {newsletter.date}")
        sections.append(f"**Total Items:** {newsletter.item_count}\n")

        # Summary if available
        if newsletter.summary:
            sections.append(f"## Summary\n\n{newsletter.summary}\n")

        # Group items by category
        by_category = self._group_by_category(newsletter.items)

        # Format each category
        for category, items in sorted(by_category.items()):
            category_title = self.CATEGORY_NAMES.get(category, category.title())
            sections.append(f"## {category_title}\n")

            for idx, item in enumerate(items, 1):
                sections.append(self._format_markdown_item(item, idx))

        # Footer
        sections.append("\n---")
        sections.append("\n*Generated by ElvAgent - AI Newsletter Curator*")

        return "\n".join(sections)

    def _group_by_category(self, items: list[NewsletterItem]) -> dict[str, list[NewsletterItem]]:
        """Group items by category."""
        by_category: dict[str, list[NewsletterItem]] = {}
        for item in items:
            category = item.category
            if category not in by_category:
                by_category[category] = []
            by_category[category].append(item)
        return by_category

    def _format_markdown_item(self, item: NewsletterItem, index: int) -> str:
        """
        Format single item for markdown.

        Args:
            item: Newsletter item
            index: Item number within category

        Returns:
            Formatted markdown string
        """
        parts = [
            f"### {index}. {item.title}",
            f"\n**Source:** {item.source.title()} | **Score:** {item.relevance_score}/10",
            f"\n{item.summary}",
            f"\n🔗 [Read more]({item.url})\n",
        ]
        return "\n".join(parts)
